import * as React from 'react';
export type IconName =
  | "Bell02"
  | "CheckDone01"
  | "ChevronSelectorVertical"
  | "Edit01"
  | "Grid01"
  | "Home02"
  | "IconChevronDown"
  | "IconEyeShow"
  | "IconOutlineArrowLeftShort"
  | "IconOutlineArrowRightShort"
  | "IconOutlineChevronDown"
  | "IconOutlinePerson"
  | "IconOutlinePlusLg"
  | "IconSearch"
  | "IconsNameArrowNarrowDownColor"
  | "IconsNameArrowNarrowUpColor"
  | "IconsNameBellColorDefault"
  | "IconsNameChatColorDefault"
  | "IconsNameCheckColorDefault"
  | "IconsNameCheckColorPrimary"
  | "IconsNameCheckFilledColorPrimary"
  | "IconsNameChevronColorDefault"
  | "IconsNameDotsVerticalColorDefault"
  | "IconsNameEditColorDefault"
  | "IconsNameFilterLinesColorDefault"
  | "IconsNameGridColorDefault"
  | "IconsNameGridColorPrimary"
  | "IconsNameHomeColorDefault"
  | "IconsNameHomeColorPrimary"
  | "IconsNameLayersColorDefault"
  | "IconsNameLayersColorPrimary"
  | "IconsNamePieChartColorDefault"
  | "IconsNamePieChartColorPrimary"
  | "IconsNamePlusColorDefault"
  | "IconsNameSearchColorDefault"
  | "IconsNameSettingsColorDefault"
  | "IconsNameTrashColorDefault"
  | "IconsNameUploadCloud01Color"
  | "IconsNameUserColorDefault"
  | "IconsNameUserColorPrimary"
  | "IconsNameXCloseColorDefault"
  | "IconsNameXCloseColorPrimary"
  | "LayersThree01"
  | "MessageChatCircle"
  | "NoteIcon"
  | "PieChart03"
  | "SearchMd"
  | "Settings03"
  | "Trash01"
  | "UserCircle"
  | "VideoCamera";
export interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName;
  size?: number | string;
}
export declare const Icon: React.FC<IconProps>;
export default Icon;
