// figma node: 50:4522 Badge number dot (392 variants)
const __variants = {
  "color=primary|style2=filled - light|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "var(--surface-brand-soft)",
    boxShadow: "inset 0 0 0 1px var(--stroke-brand-soft)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=primary|style2=outlined - solid|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "revert",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=primary|style2=outlined - light|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-brand-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=primary|style2=outlined - grey|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "var(--surface-gray-elevated-l1)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=primary|style2=filled - solid|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=primary|style2=filled - light|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "var(--surface-brand-soft)",
    boxShadow: "inset 0 0 0 1px var(--stroke-brand-soft)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=primary|style2=outlined - solid|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "revert",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=primary|style2=outlined - light|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-brand-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=primary|style2=outlined - grey|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "var(--surface-gray-elevated-l1)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=primary|style2=filled - solid|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=primary|style2=filled - light|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "var(--surface-brand-soft)",
    boxShadow: "inset 0 0 0 1px var(--stroke-brand-soft)",
  },
  "color=primary|style2=outlined - solid|type=number|size=m": { height: "calc(var(--size-7) * 1px)", minWidth: 28, backgroundColor: "revert" },
  "color=primary|style2=outlined - light|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-brand-light)",
  },
  "color=primary|style2=outlined - grey|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "var(--surface-gray-elevated-l1)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
  },
  "color=primary|style2=filled - solid|type=number|size=m": { height: "calc(var(--size-7) * 1px)", minWidth: 28 },
  "color=secondary|style2=filled - light|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "var(--surface-gray-soft)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-soft)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=secondary|style2=outlined - solid|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-solid)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=secondary|style2=outlined - light|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=secondary|style2=outlined - grey|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "var(--surface-gray-elevated-l1)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=secondary|style2=filled - solid|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "var(--surface-gray-solid)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-solid)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=secondary|style2=filled - light|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "var(--surface-gray-soft)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-soft)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=secondary|style2=outlined - solid|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-solid)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=secondary|style2=outlined - light|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=secondary|style2=outlined - grey|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "var(--surface-gray-elevated-l1)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=secondary|style2=filled - solid|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "var(--surface-gray-solid)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-solid)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=secondary|style2=filled - light|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "var(--surface-gray-soft)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-soft)",
  },
  "color=secondary|style2=outlined - solid|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-solid)",
  },
  "color=secondary|style2=outlined - light|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
  },
  "color=secondary|style2=outlined - grey|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "var(--surface-gray-elevated-l1)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
  },
  "color=secondary|style2=filled - solid|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "var(--surface-gray-solid)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-solid)",
  },
  "color=success|style2=filled - light|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "var(--surface-success-soft)",
    boxShadow: "inset 0 0 0 1px var(--stroke-success-soft)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=success|style2=outlined - solid|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-success-solid)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=success|style2=outlined - light|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-success-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=success|style2=outlined - grey|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "var(--surface-gray-elevated-l1)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=success|style2=filled - light|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "var(--surface-success-soft)",
    boxShadow: "inset 0 0 0 1px var(--stroke-success-soft)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=success|style2=filled - solid|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "var(--surface-success-solid)",
    boxShadow: "inset 0 0 0 1px var(--stroke-success-solid)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=success|style2=filled - light|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "var(--surface-success-soft)",
    boxShadow: "inset 0 0 0 1px var(--stroke-success-soft)",
  },
  "color=success|style2=outlined - solid|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-success-solid)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=success|style2=outlined - light|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-success-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=success|style2=outlined - grey|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "var(--surface-gray-elevated-l1)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=success|style2=filled - solid|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "var(--surface-success-solid)",
    boxShadow: "inset 0 0 0 1px var(--stroke-success-solid)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=danger|style2=filled - light|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "var(--surface-error-soft)",
    boxShadow: "inset 0 0 0 1px var(--stroke-error-soft)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=success|style2=outlined - solid|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-success-solid)",
  },
  "color=success|style2=outlined - light|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-success-light)",
  },
  "color=success|style2=outlined - grey|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "var(--surface-gray-elevated-l1)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
  },
  "color=success|style2=filled - solid|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "var(--surface-success-solid)",
    boxShadow: "inset 0 0 0 1px var(--stroke-success-solid)",
  },
  "color=danger|style2=filled - light|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "var(--surface-error-soft)",
    boxShadow: "inset 0 0 0 1px var(--stroke-error-soft)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=danger|style2=outlined - solid|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-error-solid)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=danger|style2=outlined - light|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-error-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=danger|style2=outlined - grey|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "var(--surface-gray-elevated-l1)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=danger|style2=filled - light|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "var(--surface-error-soft)",
    boxShadow: "inset 0 0 0 1px var(--stroke-error-soft)",
  },
  "color=danger|style2=filled - solid|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "var(--surface-error-solid)",
    boxShadow: "inset 0 0 0 1px var(--stroke-error-solid)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=danger|style2=outlined - solid|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-error-solid)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=danger|style2=outlined - light|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-error-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=danger|style2=outlined - grey|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "var(--surface-gray-elevated-l1)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=danger|style2=filled - solid|type=number|size=s": {
    height: "calc(var(--size-6) * 1px)",
    minWidth: 24,
    backgroundColor: "var(--surface-error-solid)",
    boxShadow: "inset 0 0 0 1px var(--stroke-error-solid)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=danger|style2=outlined - solid|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-error-solid)",
  },
  "color=danger|style2=outlined - light|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "revert",
    boxShadow: "inset 0 0 0 1px var(--stroke-error-light)",
  },
  "color=danger|style2=outlined - grey|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "var(--surface-gray-elevated-l1)",
    boxShadow: "inset 0 0 0 1px var(--stroke-gray-light)",
  },
  "color=danger|style2=filled - solid|type=number|size=m": {
    height: "calc(var(--size-7) * 1px)",
    minWidth: 28,
    backgroundColor: "var(--surface-error-solid)",
    boxShadow: "inset 0 0 0 1px var(--stroke-error-solid)",
  },
  "color=warning|style2=filled - light|type=number|size=xs": {
    height: "calc(var(--size-5) * 1px)",
    minWidth: 20,
    backgroundColor: "var(--surface-warning-soft)",
    boxShadow: "inset 0 0 0 1px var(--stroke-warning-soft)",
    paddingLeft: "calc(var(--spacing-0-5) * 1px)",
    paddingRight: "calc(var(--spacing-0-5) * 1px)",
    padding: "0px 2px 0px 2px",
    boxSizing: "border-box",
  },
  "color=warning|style2=filled - light|type=number|size=xxs": { backgroundColor: "var(--surface-warning-soft)", boxShadow: "inset 0 0 0 1px var(--stroke-warning-soft)" },
  "color=danger|style2=filled - light|type=number|size=xxs": { backgroundColor: "var(--surface-error-soft)", boxShadow: "inset 0 0 0 1px var(--stroke-error-soft)" },
  "color=success|style2=filled - light|type=number|size=xxs": { backgroundColor: "var(--surface-success-soft)", boxShadow: "inset 0 0 0 1px var(--stroke-success-soft)" },
  // …+327 more variants not captured: "color=secondary|style2=filled - light|type=number|size=xxs", "color=primary|style2=filled - light|type=number|size=xxs", "color=warning|style2=filled - light|type=number|size=s", "color=warning|style2=outlined - solid|type=number|size=xs", "color=warning|style2=outlined - light|type=number|size=xs", "color=warning|style2=outlined - grey|type=number|size=xs", "color=warning|style2=filled - solid|type=number|size=xs", "color=warning|style2=outlined - solid|type=number|size=xxs", "color=warning|style2=outlined - light|type=number|size=xxs", "color=warning|style2=outlined - grey|type=number|size=xxs", …
};
const __venc = (v) => String(v).replace(/[%|=]/g, encodeURIComponent);
const __vkey = (p) => "color=" + __venc(p.color) + '|' + "style2=" + __venc(p.style2) + '|' + "type=" + __venc(p.type) + '|' + "size=" + __venc(p.size);

export function BadgeNumberDot(_p = {}) {
  const props = { ..._p, color: _p.color ?? "primary", number: _p.number ?? "3", style2: _p.style2 ?? "filled - solid", type: _p.type ?? "number", size: _p.size ?? "xxs" };
  const __vs = __variants[__vkey(props)] ?? {};
  return (
    <div className={props.className} style={{
      width: "fit-content",
      height: "calc(var(--size-4) * 1px)",
      minWidth: 16,
      overflow: "hidden",
      borderRadius: 9999,
      backgroundColor: "var(--surface-brand-solid)",
      boxShadow: "inset 0 0 0 1px var(--stroke-brand-solid)",
      display: "flex",
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      flexWrap: "nowrap",
      paddingLeft: "calc(var(--spacing-0) * 1px)",
      paddingTop: "calc(var(--spacing-0) * 1px)",
      paddingRight: "calc(var(--spacing-0) * 1px)",
      paddingBottom: "calc(var(--spacing-0) * 1px)",
      position: "relative",
      ...__vs, ...props.style,
    }}>
      <div style={{
        position: "relative",
        display: "flex",
        flexDirection: "row",
        padding: "0px 4px 0px 4px",
        justifyContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        boxSizing: "border-box",
        paddingLeft: "calc(var(--spacing-1) * 1px)",
        paddingRight: "calc(var(--spacing-1) * 1px)",
        flexShrink: 0,
        alignSelf: "stretch",
      }}>
        <span style={{
          position: "relative",
          fontFamily: "Inter, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
          fontWeight: 600,
          fontSize: 10,
          whiteSpace: "nowrap",
          lineHeight: "14px",
          letterSpacing: "0.005em",
          color: "var(--text-brand-on-solid-background)",
          flexShrink: 0,
          alignSelf: "stretch",
        }}>{props.number}</span>
      </div>
    </div>
  );
}
export default BadgeNumberDot;
